services:
  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  task-api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_LOGIN=${DB_LOGIN}
      - DB_PASS=${DB_PASS}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
    ports:
      - 8000:8000