name: Workflow for TaskAPI CI
run-name: Workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DB_LOGIN: postgres
  DB_PASS: postgres
  DB_HOST: localhost
  DB_NAME: db
  DB_PORT: 6000
  TEST_DB_LOGIN: postgres
  TEST_DB_PASS: postgres
  TEST_DB_HOST: localhost
  TEST_DB_PORT: 6000
  TEST_DB_NAME: db

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 6000:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: pytest tests/ -v